/* listings.js */
const SHEET_CSV = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQsZyN4A56Hfw0uBQL8Bvsw5dUiyeUmKTn9m_lRtIkmhkGk7kXrec6IjeFnddA0GYrelrOfmfWdtOLn/pub?output=csv';
function csvToJson(csv){const lines=csv.trim().split(/\r?\n/);const headers=lines.shift().split(',').map(h=>h.trim().toLowerCase());return lines.map(l=>{const parts=[];let cur='',inQ=false;for(let i=0;i<l.length;i++){const c=l[i];if(c=='"'){if(inQ&&l[i+1]=='"'){cur+='"';i++;}else inQ=!inQ;}else if(c==','&&!inQ){parts.push(cur);cur='';}else{cur+=c;}}parts.push(cur);const obj={};headers.forEach((h,idx)=>obj[h]=(parts[idx]||'').trim());return obj;});}
function prettyPrice(p){if(!p)return'';const n=Number(String(p).replace(/[^0-9.]/g,''));if(!isFinite(n))return p;return n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});}
async function loadListings(){const grid=document.querySelector('#grid');const count=document.querySelector('#count');const res=await fetch(SHEET_CSV,{cache:'no-store'});const txt=await res.text();const rows=csvToJson(txt).filter(r=>r.address);window.__LISTINGS=rows;populateFilters(rows);render(rows);
function render(items){grid.innerHTML='';items.forEach(r=>{const img=r.photo_url||r.photo||r.image||'assets/b75192561f99452dd42f2f75219f9eaa-p_e.webp';const addr=r.address||'';const hood=r.neighborhood||r.area||'';const beds=r.beds||r.bedrooms||'';const baths=r.baths||r.bathrooms||'';const type=r.type||r.home_type||'';const price=prettyPrice(r.price);const zurl=r.zillow_url||r.url||'#';const el=document.createElement('div');el.className='tile';el.innerHTML=`<img src="${img}" alt="${addr}"><div class="body"><div class="addr">${addr}</div><div class="info">${hood?hood+' • ':''}${beds} Beds • ${baths} Baths • ${type}</div><div class="price">${price}</div></div><div class="more"><a href="${zurl}" target="_blank" rel="noopener">View Details →</a><span>on Zillow</span></div>`;grid.appendChild(el);});count.textContent=`Showing ${items.length} listing${items.length!==1?'s':''}`;}
function applyFilters(){const hood=document.querySelector('#f-hood').value;const type=document.querySelector('#f-type').value;const minp=Number(document.querySelector('#f-min').value||0);const maxp=Number(document.querySelector('#f-max').value||999999999);const beds=Number(document.querySelector('#f-beds').value||0);const out=window.__LISTINGS.filter(r=>{const price=Number(String(r.price||'').replace(/[^0-9.]/g,''))||0;const hoodOk=!hood||(r.neighborhood||r.area||'').toLowerCase()===hood.toLowerCase();const typeOk=!type||(r.type||r.home_type||'').toLowerCase()===type.toLowerCase();const bedOk=!beds||Number(r.beds||r.bedrooms||0)>=beds;return hoodOk&&typeOk&&price>=minp&&price<=maxp&&bedOk;});render(out);}
document.querySelectorAll('.filters select, .filters input').forEach(el=>el.addEventListener('change',applyFilters));function populateFilters(data){const hoods=[...new Set(data.map(r=>(r.neighborhood||r.area||'').trim()).filter(Boolean))].sort();const types=[...new Set(data.map(r=>(r.type||r.home_type||'').trim()).filter(Boolean))].sort();const selH=document.querySelector('#f-hood');const selT=document.querySelector('#f-type');hoods.forEach(h=>selH.insertAdjacentHTML('beforeend',`<option>${h}</option>`));types.forEach(t=>selT.insertAdjacentHTML('beforeend',`<option>${t}</option>`));}}
document.addEventListener('DOMContentLoaded',loadListings);
